#!/usr/bin/env python3
from __future__ import annotations

import argparse
from datetime import datetime
from difflib import SequenceMatcher
import json
from pathlib import Path
import re
import shutil
import unicodedata


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_DOWNLOAD_DIR = Path.home() / "Downloads" / "Spotify Transcript Collector"


def _latest_manifest() -> Path:
    manifests = sorted((ROOT / "data" / "runs").glob("*-manifest.json"))
    if not manifests:
        raise SystemExit("No manifest files found. Run scripts/check_new_episodes.py first.")
    return manifests[-1]


def _format_time(value: str | None) -> str:
    if not value:
        return "unknown time"
    dt = datetime.fromisoformat(value)
    return dt.astimezone().strftime("%Y-%m-%d %H:%M %Z")


def _normalize(value: str | None) -> str:
    if not value:
        return ""
    value = unicodedata.normalize("NFKC", value).casefold()
    value = value.replace("&", " and ")
    value = re.sub(r"[\u2018\u2019\u201c\u201d]", "'", value)
    value = re.sub(r"[^a-z0-9\u4e00-\u9fff]+", " ", value)
    return re.sub(r"\s+", " ", value).strip()


def _similarity(left: str, right: str) -> float:
    left_norm = _normalize(left)
    right_norm = _normalize(right)
    if not left_norm or not right_norm:
        return 0.0
    if left_norm == right_norm:
        return 1.0
    if left_norm in right_norm or right_norm in left_norm:
        return 0.92
    return SequenceMatcher(None, left_norm, right_norm).ratio()


def _load_transcript(path: Path) -> dict[str, object] | None:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    if not isinstance(data, dict):
        return None
    return data


def _find_downloaded_transcripts(download_dir: Path) -> list[dict[str, object]]:
    rows: list[dict[str, object]] = []
    if not download_dir.exists():
        return rows

    for path in sorted(download_dir.glob("*.json")):
        data = _load_transcript(path)
        if not data:
            continue
        segments = data.get("segments")
        rows.append(
            {
                "path": str(path),
                "source": data.get("source"),
                "spotify_episode_id": data.get("spotifyEpisodeId"),
                "episode_url": data.get("episodeUrl"),
                "podcast_name": data.get("podcastName"),
                "episode_title": data.get("episodeTitle"),
                "published_date": data.get("publishedDate"),
                "language": data.get("transcriptLanguage"),
                "is_auto_generated": data.get("isAutoGenerated"),
                "segments_count": len(segments) if isinstance(segments, list) else 0,
            }
        )
    return rows


def _score_candidate(episode: dict[str, object], transcript: dict[str, object]) -> tuple[float, dict[str, float]]:
    title_score = _similarity(
        str(episode.get("episode_title") or ""),
        str(transcript.get("episode_title") or ""),
    )
    podcast_score = _similarity(
        str(episode.get("podcast_title") or ""),
        str(transcript.get("podcast_name") or ""),
    )
    score = title_score * 0.78 + podcast_score * 0.22
    return score, {"title": round(title_score, 3), "podcast": round(podcast_score, 3)}


def _match_transcript(
    episode: dict[str, object],
    transcripts: list[dict[str, object]],
    used_paths: set[str],
) -> dict[str, object] | None:
    candidates: list[tuple[float, dict[str, float], dict[str, object]]] = []
    for transcript in transcripts:
        path = str(transcript["path"])
        if path in used_paths:
            continue
        score, components = _score_candidate(episode, transcript)
        candidates.append((score, components, transcript))

    if not candidates:
        return None

    candidates.sort(key=lambda item: item[0], reverse=True)
    score, components, transcript = candidates[0]
    if score < 0.82:
        return None
    used_paths.add(str(transcript["path"]))
    return {
        "match_score": round(score, 3),
        "score_components": components,
        **transcript,
    }


def build(manifest_path: Path, download_dir: Path) -> tuple[Path, Path]:
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    transcripts = _find_downloaded_transcripts(download_dir)
    used_paths: set[str] = set()

    episode_rows = []
    for index, episode in enumerate(manifest["new_episodes"], 1):
        match = _match_transcript(episode, transcripts, used_paths)
        episode_rows.append(
            {
                "index": index,
                "podcast_title": episode["podcast_title"],
                "episode_title": episode["episode_title"],
                "published_at": episode["published_at"],
                "rss_episode_url": episode["episode_url"],
                "audio_url": episode["audio_url"],
                "guid": episode["guid"],
                "description_preview": episode["description_preview"],
                "transcript": match,
                "status": "ready" if match else "missing_transcript",
            }
        )

    matched_count = sum(1 for row in episode_rows if row["transcript"])
    evidence_pack = {
        "run_id": manifest["run_id"],
        "created_at": datetime.now().astimezone().isoformat(),
        "manifest_path": str(manifest_path),
        "download_dir": str(download_dir),
        "sort_rule": manifest["sort_rule"],
        "summary": {
            "episode_count": len(episode_rows),
            "transcript_count": len(transcripts),
            "matched_count": matched_count,
            "missing_count": len(episode_rows) - matched_count,
        },
        "episodes": episode_rows,
        "unmatched_transcripts": [
            transcript for transcript in transcripts if str(transcript["path"]) not in used_paths
        ],
    }

    output_json = ROOT / "data" / "runs" / f"{manifest['run_id']}-evidence-pack.json"
    output_json.parent.mkdir(parents=True, exist_ok=True)
    output_json.write_text(json.dumps(evidence_pack, ensure_ascii=False, indent=2), encoding="utf-8")

    output_md = ROOT / "reports" / "markdown" / f"{manifest['run_id']}-evidence-pack.md"
    output_md.parent.mkdir(parents=True, exist_ok=True)
    _write_markdown(output_md, evidence_pack)
    return output_json, output_md


def _write_markdown(path: Path, pack: dict[str, object]) -> None:
    summary = pack["summary"]
    lines = [
        f"# Evidence Pack {pack['run_id']}",
        "",
        f"- 生成时间：{_format_time(str(pack['created_at']))}",
        f"- Episode 数量：{summary['episode_count']}",
        f"- 已匹配 transcript：{summary['matched_count']}",
        f"- 缺 transcript：{summary['missing_count']}",
        f"- 下载目录：`{pack['download_dir']}`",
        "",
        "## 明细",
        "",
    ]

    for episode in pack["episodes"]:
        transcript = episode["transcript"]
        lines.extend(
            [
                f"### {episode['index']}. {episode['episode_title']}",
                "",
                f"- 播客：{episode['podcast_title']}",
                f"- 发布时间：{_format_time(episode['published_at'])}",
                f"- 状态：`{episode['status']}`",
            ]
        )
        if transcript:
            lines.extend(
                [
                    f"- Transcript 文件：`{transcript['path']}`",
                    f"- 匹配分数：{transcript['match_score']}",
                    f"- Spotify Episode ID：`{transcript.get('spotify_episode_id') or 'unknown'}`",
                    f"- 字幕段落数：{transcript['segments_count']}",
                    f"- 字幕语言：{transcript.get('language') or 'unknown'}",
                ]
            )
        else:
            lines.append("- Transcript 文件：缺失")
        lines.append("")

    unmatched = pack.get("unmatched_transcripts") or []
    if unmatched:
        lines.extend(["## 未匹配的下载字幕", ""])
        for transcript in unmatched:
            lines.append(f"- `{transcript['path']}`")
        lines.append("")

    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Build a transcript evidence pack for Gemini.")
    parser.add_argument("manifest", nargs="?", type=Path, help="Manifest JSON path. Defaults to latest.")
    parser.add_argument(
        "--download-dir",
        type=Path,
        default=DEFAULT_DOWNLOAD_DIR,
        help="Directory containing Spotify Transcript Downloader JSON files.",
    )
    args = parser.parse_args()

    output_json, output_md = build(args.manifest or _latest_manifest(), args.download_dir)
    print(output_json)
    print(output_md)


if __name__ == "__main__":
    main()
