#!/usr/bin/env python3
from __future__ import annotations

import argparse
from datetime import datetime
import json
from pathlib import Path
import shutil
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_PROMPT_TEMPLATE = ROOT / "docs" / "gemini" / "Gemini最终Prompt模板.md"
DEFAULT_PROTOCOL = ROOT / "docs" / "gemini" / "Gemini研报生成协议.md"
DEFAULT_REVIEW_CHECKLIST = ROOT / "docs" / "gemini" / "Gemini研报复查清单.md"


def _latest_evidence_pack() -> Path:
    packs = sorted((ROOT / "data" / "runs").glob("*-evidence-pack.json"))
    if not packs:
        raise SystemExit("No evidence pack files found. Run scripts/build_evidence_pack.py first.")
    return packs[-1]


def _read_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _write_json(path: Path, data: Any) -> None:
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")


def _segment_text(segment: dict[str, Any]) -> str:
    speaker = segment.get("speaker")
    timestamp = segment.get("timestamp") or _format_seconds(segment.get("start"))
    text = str(segment.get("text") or "").strip()
    if speaker:
        return f"[{timestamp}] {speaker}: {text}"
    return f"[{timestamp}] {text}"


def _format_seconds(value: Any) -> str:
    try:
        seconds = int(float(value))
    except (TypeError, ValueError):
        return "unknown"
    hours, remainder = divmod(seconds, 3600)
    minutes, seconds = divmod(remainder, 60)
    if hours:
        return f"{hours}:{minutes:02d}:{seconds:02d}"
    return f"{minutes}:{seconds:02d}"


def _load_transcript(transcript_meta: dict[str, Any] | None) -> dict[str, Any] | None:
    if not transcript_meta:
        return None
    path_value = transcript_meta.get("path")
    if not path_value:
        return None

    path = Path(str(path_value))
    if not path.is_absolute():
        path = ROOT / path
    if not path.exists():
        return {
            "error": "transcript_file_not_found",
            "path": str(path),
            "segments": [],
            "plain_text": "",
        }

    data = _read_json(path)
    segments = data.get("segments")
    if not isinstance(segments, list):
        segments = []

    normalized_segments = []
    for segment in segments:
        if not isinstance(segment, dict):
            continue
        normalized_segments.append(
            {
                "timestamp": segment.get("timestamp") or _format_seconds(segment.get("start")),
                "start": segment.get("start"),
                "end": segment.get("end"),
                "speaker": segment.get("speaker"),
                "text": segment.get("text"),
            }
        )

    return {
        "source": data.get("source"),
        "captured_at": data.get("capturedAt"),
        "spotify_episode_id": data.get("spotifyEpisodeId"),
        "episode_url": data.get("episodeUrl"),
        "podcast_name": data.get("podcastName"),
        "episode_title": data.get("episodeTitle"),
        "published_date": data.get("publishedDate"),
        "transcript_language": data.get("transcriptLanguage"),
        "is_auto_generated": data.get("isAutoGenerated"),
        "path": str(path),
        "segments": normalized_segments,
        "plain_text": "\n".join(_segment_text(segment) for segment in normalized_segments),
    }


def _episode_manifest_row(episode: dict[str, Any]) -> dict[str, Any]:
    transcript = episode.get("transcript") or {}
    return {
        "index": episode["index"],
        "podcast_title": episode["podcast_title"],
        "episode_title": episode["episode_title"],
        "published_at": episode["published_at"],
        "rss_episode_url": episode.get("rss_episode_url"),
        "spotify_episode_url": transcript.get("episode_url") if isinstance(transcript, dict) else None,
        "audio_url": episode.get("audio_url"),
        "guid": episode.get("guid"),
        "description_preview": episode.get("description_preview"),
        "transcript_source": transcript.get("source") if isinstance(transcript, dict) else None,
        "transcript_language": transcript.get("language") if isinstance(transcript, dict) else None,
        "transcript_segments_count": transcript.get("segments_count") if isinstance(transcript, dict) else None,
        "transcript_status": episode.get("status"),
    }


def _build_full_evidence(pack: dict[str, Any], evidence_pack_path: Path) -> dict[str, Any]:
    episodes = []
    for episode in pack["episodes"]:
        transcript_meta = episode.get("transcript")
        transcript = _load_transcript(transcript_meta if isinstance(transcript_meta, dict) else None)
        episodes.append(
            {
                "index": episode["index"],
                "podcast_title": episode["podcast_title"],
                "episode_title": episode["episode_title"],
                "published_at": episode["published_at"],
                "rss_episode_url": episode.get("rss_episode_url"),
                "spotify_episode_url": (
                    transcript_meta.get("episode_url") if isinstance(transcript_meta, dict) else None
                ),
                "audio_url": episode.get("audio_url"),
                "guid": episode.get("guid"),
                "description_preview": episode.get("description_preview"),
                "status": episode.get("status"),
                "transcript_match": transcript_meta,
                "transcript": transcript,
            }
        )

    return {
        "run_id": pack["run_id"],
        "created_at": datetime.now().astimezone().isoformat(),
        "source_evidence_pack": str(evidence_pack_path),
        "source_manifest": pack.get("manifest_path"),
        "sort_rule": pack.get("sort_rule"),
        "summary": pack["summary"],
        "episodes": episodes,
    }


def _write_transcript_markdown(path: Path, full_evidence: dict[str, Any]) -> None:
    lines = [
        f"# Transcript Evidence {full_evidence['run_id']}",
        "",
        "Use these timestamped transcript blocks as the primary evidence base for the report.",
        "",
    ]
    for episode in full_evidence["episodes"]:
        transcript = episode.get("transcript") or {}
        lines.extend(
            [
                f"## {episode['index']}. {episode['episode_title']}",
                "",
                f"- Podcast: {episode['podcast_title']}",
                f"- Published: {episode['published_at']}",
                f"- Spotify URL: {episode.get('spotify_episode_url') or 'unknown'}",
                f"- RSS URL: {episode.get('rss_episode_url') or 'unknown'}",
                f"- Transcript source: {transcript.get('source') or 'missing'}",
                "",
                "```text",
                transcript.get("plain_text") or "TRANSCRIPT MISSING",
                "```",
                "",
            ]
        )
    path.write_text("\n".join(lines), encoding="utf-8")


def _write_prompt(path: Path, manifest_name: str, evidence_name: str) -> None:
    prompt_template = DEFAULT_PROMPT_TEMPLATE.read_text(encoding="utf-8")
    protocol = DEFAULT_PROTOCOL.read_text(encoding="utf-8")
    checklist = DEFAULT_REVIEW_CHECKLIST.read_text(encoding="utf-8")
    lines = [
        "# Gemini Input Prompt",
        "",
        "请读取同目录下的两个 JSON 文件，并严格按照以下协议生成播客情报研报。",
        "",
        f"- Episode Manifest: `{manifest_name}`",
        f"- Transcript Evidence Pack: `{evidence_name}`",
        "",
        "重要执行约束：",
        "",
        "- 第二部分必须严格覆盖 Manifest 中的全部 episode，数量和顺序完全一致。",
        "- 有 Spotify transcript 的 episode，必须从 transcript 的 `segments` 或 `plain_text` 中取证。",
        "- 关键金句和证据锚点必须带时间戳。",
        "- 背景资料可以用于解释意义，但不得写成播客嘉宾原话。",
        "- 输出完成后，先按复查清单自检，再给出最终研报。",
        "",
        "---",
        "",
        protocol,
        "",
        "---",
        "",
        prompt_template,
        "",
        "---",
        "",
        checklist,
    ]
    path.write_text("\n".join(lines), encoding="utf-8")


def _write_handoff(path: Path, run_id: str, output_dir: Path, files: list[Path], summary: dict[str, Any]) -> None:
    lines = [
        f"# Gemini Input Package {run_id}",
        "",
        "This folder is ready to upload or paste into Gemini.",
        "",
        "## Files",
        "",
    ]
    for file_path in files:
        lines.append(f"- `{file_path.name}`")
    lines.extend(
        [
            "",
            "## Coverage",
            "",
            f"- Episodes: {summary.get('episode_count')}",
            f"- Matched transcripts: {summary.get('matched_count')}",
            f"- Missing transcripts: {summary.get('missing_count')}",
            "",
            "## Suggested Gemini workflow",
            "",
            "1. Upload `episode-manifest.json`, `transcript-evidence-full.json`, and `gemini-prompt.md`.",
            "2. Ask Gemini to generate the report from `gemini-prompt.md`.",
            "3. Save Gemini's output as a Markdown report so Codex can run the review checker next.",
            "",
            f"Package path: `{output_dir}`",
            "",
        ]
    )
    path.write_text("\n".join(lines), encoding="utf-8")


def build(evidence_pack_path: Path, output_dir: Path | None = None) -> Path:
    evidence_pack_path = evidence_pack_path.resolve()
    pack = _read_json(evidence_pack_path)
    run_id = pack["run_id"]
    if output_dir is None:
        output_dir = ROOT / "data" / "gemini_inputs" / run_id
    output_dir.mkdir(parents=True, exist_ok=True)

    manifest_path = Path(str(pack["manifest_path"]))
    if not manifest_path.is_absolute():
        manifest_path = ROOT / manifest_path

    manifest = _read_json(manifest_path)
    episode_manifest = {
        "run_id": run_id,
        "created_at": datetime.now().astimezone().isoformat(),
        "source_manifest": str(manifest_path),
        "sort_rule": manifest.get("sort_rule"),
        "summary": manifest.get("summary"),
        "episodes": [_episode_manifest_row(episode) for episode in pack["episodes"]],
    }
    full_evidence = _build_full_evidence(pack, evidence_pack_path)

    original_manifest_out = output_dir / "source-manifest-original.json"
    shutil.copyfile(manifest_path, original_manifest_out)

    manifest_out = output_dir / "episode-manifest.json"
    evidence_out = output_dir / "transcript-evidence-full.json"
    transcript_md_out = output_dir / "transcript-evidence-full.md"
    prompt_out = output_dir / "gemini-prompt.md"
    handoff_out = output_dir / "README.md"

    _write_json(manifest_out, episode_manifest)
    _write_json(evidence_out, full_evidence)
    _write_transcript_markdown(transcript_md_out, full_evidence)
    _write_prompt(prompt_out, manifest_out.name, evidence_out.name)
    _write_handoff(
        handoff_out,
        run_id,
        output_dir,
        [manifest_out, evidence_out, transcript_md_out, prompt_out, original_manifest_out],
        pack["summary"],
    )
    return output_dir


def main() -> None:
    parser = argparse.ArgumentParser(description="Build a Gemini-ready input package from an evidence pack.")
    parser.add_argument("evidence_pack", nargs="?", type=Path, help="Evidence pack JSON path. Defaults to latest.")
    parser.add_argument("--output-dir", type=Path, help="Output directory. Defaults to data/gemini_inputs/<run_id>.")
    args = parser.parse_args()

    output_dir = build(args.evidence_pack or _latest_evidence_pack(), args.output_dir)
    print(output_dir)


if __name__ == "__main__":
    main()
