#!/usr/bin/env python3
from __future__ import annotations

import argparse
from html import unescape
import json
from pathlib import Path
import re
import urllib.request


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUT_DIR = ROOT / "data" / "transcripts" / "spotify_en"
TIMING_RE = re.compile(
    r"^(?P<start>\d{1,2}:\d{2}(?::\d{2})?[.,]\d{3})\s+-->\s+"
    r"(?P<end>\d{1,2}:\d{2}(?::\d{2})?[.,]\d{3})"
)
TAG_RE = re.compile(r"<[^>]+>")


def clean_filename(value: object) -> str:
    return re.sub(r'[\\/:*?"<>|#%]', "_", str(value or "unknown")).strip()


def parse_time(value: str) -> float:
    parts = value.replace(",", ".").split(":")
    seconds = float(parts[-1])
    minutes = int(parts[-2])
    hours = int(parts[-3]) if len(parts) == 3 else 0
    return hours * 3600 + minutes * 60 + seconds


def format_timestamp(seconds: float) -> str:
    whole = max(0, int(seconds))
    hours, remainder = divmod(whole, 3600)
    minutes, secs = divmod(remainder, 60)
    if hours:
        return f"{hours}:{minutes:02d}:{secs:02d}"
    return f"{minutes}:{secs:02d}"


def clean_text(lines: list[str]) -> str:
    text = " ".join(line.strip() for line in lines if line.strip())
    return re.sub(r"\s+", " ", unescape(TAG_RE.sub("", text))).strip()


def parse_vtt(content: str) -> list[dict[str, object]]:
    lines = content.replace("\r\n", "\n").replace("\r", "\n").split("\n")
    segments: list[dict[str, object]] = []
    index = 0
    while index < len(lines):
        match = TIMING_RE.match(lines[index].strip())
        if not match:
            index += 1
            continue
        start = parse_time(match.group("start"))
        end = parse_time(match.group("end"))
        index += 1
        text_lines: list[str] = []
        while index < len(lines) and lines[index].strip():
            text_lines.append(lines[index])
            index += 1
        text = clean_text(text_lines)
        if text:
            segments.append(
                {
                    "start": start,
                    "end": end,
                    "timestamp": format_timestamp(start),
                    "speaker": None,
                    "text": text,
                }
            )
    return segments


def read_vtt(episode: dict[str, object], vtt_file: Path | None) -> tuple[str, str]:
    transcript_url = str(episode.get("transcript_url") or "")
    if vtt_file:
        return vtt_file.read_text(encoding="utf-8-sig"), transcript_url or str(vtt_file)
    if not transcript_url:
        raise SystemExit("Selected manifest episode has no transcript_url; pass --vtt-file.")
    with urllib.request.urlopen(transcript_url, timeout=120) as response:
        return response.read().decode("utf-8-sig"), transcript_url


def main() -> None:
    parser = argparse.ArgumentParser(description="Import an official RSS WebVTT transcript into the report archive.")
    parser.add_argument("--manifest", type=Path, required=True)
    parser.add_argument("--index", type=int, required=True, help="One-based episode index in the manifest.")
    parser.add_argument("--vtt-file", type=Path)
    parser.add_argument("--out-dir", type=Path, default=DEFAULT_OUT_DIR)
    args = parser.parse_args()

    manifest = json.loads(args.manifest.read_text(encoding="utf-8"))
    episodes = manifest.get("new_episodes") or manifest.get("episodes") or []
    if args.index < 1 or args.index > len(episodes):
        raise SystemExit(f"Episode index {args.index} is outside 1..{len(episodes)}.")
    episode = episodes[args.index - 1]
    content, source_url = read_vtt(episode, args.vtt_file)
    segments = parse_vtt(content)
    if not segments:
        raise SystemExit("Official VTT contained no parseable transcript cues.")

    guid = str(episode.get("guid") or "").strip()
    identity = guid or f"rss-vtt-{args.index}"
    identity_suffix = identity.split(":", 1)[-1]
    published_date = str(episode.get("published_at") or "")[:10]
    payload = {
        "source": "official_rss_vtt",
        "spotifyEpisodeId": identity,
        "episodeUrl": episode.get("episode_url"),
        "transcriptUrl": source_url,
        "podcastName": episode.get("podcast_title"),
        "episodeTitle": episode.get("episode_title"),
        "publishedDate": published_date,
        "duration": episode.get("duration"),
        "transcriptLanguage": "en",
        "isAutoGenerated": "unknown",
        "segments": segments,
        "debugLogs": ["Imported from the official RSS WebVTT transcript URL."],
    }
    filename = (
        f"{published_date} - {clean_filename(episode.get('podcast_title'))} - "
        f"{clean_filename(episode.get('episode_title'))} - rss-vtt-{clean_filename(identity_suffix)}.json"
    )
    args.out_dir.mkdir(parents=True, exist_ok=True)
    output_path = args.out_dir / filename
    output_path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"path={output_path}")
    print(f"segments={len(segments)}")


if __name__ == "__main__":
    main()
